### ISSUE TITLE
Undocumented code

### ISSUE THREAD

**Issue by rossGardiner** [albanjoseph/Signapse#1]
Advances in the code-base are currently undocumented. We should try to add documentation using Doxygen to all created classes and functionality. 

Documentation will lag advances in the code-base. For this reason, a docs branch should be made from `dev` at commit `74631ccd8b93da8b4ca26b5673dfbe0d41a393d5`. Continuous review will see documentation built for subsequent advances in the code.

**Comment by Saweenbarra** [comment]
Fixed in commit 852b09d8ee2687a684c85e6e167d22750b66a8f1
