### ISSUE TITLE
Wiki Entries! 

### ISSUE THREAD

**Issue by rossGardiner** [albanjoseph/Signapse#23]
We must get in some wiki entries to ensure we get the marks we deserve for the course! From reading the mark scheme, here are some some suggested wiki entries: 
- Quick Start
  (Set of instructions and commands to install Signapse from fresh on both RPi and Ubuntu)
- How it Works 
  (Could include a description of the legacy pipeline and how this is improved with the callbacks re-design)
- Documentation
  (Links to the hosted docs, already exists I think?)
- Real-time Evaluation
  (This is explicit in the mark scheme, **not sure how to work on this, open to suggestions**)
- Unit Testing 
  (Describes the unit testing methodology, tests and google-test framework)
- Social Media
  (Some spraff about our social media strategy and getting published in two tech journals)
- Organisation/team management 
  (Must describe how we've successfully used git to organise and manage ourselves. Could also describe different roles in our team)

**Comment by rossGardiner** [comment]
done some stuff [here](https://github.com/albanjoseph/Signapse/wiki/Software-Development-Strategy)

**Comment by Saweenbarra** [comment]
Social media wiki entry created [here](https://github.com/albanjoseph/Signapse/wiki/Social-Media-Strategy).
