### ISSUE TITLE
Testing 

### ISSUE THREAD

**Issue by rossGardiner** [albanjoseph/Signapse#4]
We should build integration tests including linting, compiling and unit tests. An integration machine could be set up and run to help us continuously evaluate our software and prepare for subsequent releases

**Comment by Saweenbarra** [comment]
A test has been set up to build the code upon a commit to the dev branch [cmake_build.yml](https://github.com/albanjoseph/Signapse/blob/main/.github/workflows/cmake_build.yml).
It simply runs the automatic installation process as detailed by the [Installation guide wiki](https://github.com/albanjoseph/Signapse/wiki/Installation-Guide)

**Comment by Saweenbarra** [comment]
Documentation is being automatically generated and committed to the `gh-pages` branch where it can be viewed at https://albanjoseph.github.io/Signapse/html/index.html

**Comment by rossGardiner** [comment]
29 unit tests have been written using the google-test framework, suitable for milestone 2. Although more testing is required for better code coverage
